"""Typings for queries generated by aiosql"""
import datetime
from typing import Dict, List, Literal

from asyncpg import Connection, Record

class UsersQueriesMixin:
    async def get_user_by_email(self, conn: Connection, *, email: str) -> Record: ...
    async def get_user_by_username(
        self, conn: Connection, *, username: str
    ) -> Record: ...
    async def create_new_user(
        self,
        conn: Connection,
        *,
        username: str,
        email: str,
        created_at: datetime.datetime,
        updated_at: datetime.datetime,
        salt: str,
        hashed_password: str,
        is_active: bool,
    ) -> Record: ...

class StatusesQueriesMixin:
    async def get_status_by_id(self, conn: Connection, *, status_id: int) -> Record: ...
    async def get_statuses_by_header_id(
        self, conn: Connection, *, header_id: int
    ) -> Record: ...

class MessagesQueriesMixin:
    async def get_message_by_id(
        self, conn: Connection, *, message_id: int
    ) -> Record: ...
    async def get_message_numbers(
        self, conn: Connection, *, message_id: int
    ) -> Record: ...
    async def create_message(
        self,
        conn: Connection,
        *,
        content: str,
        user_id: int,
        status_code: int,
        created_at: datetime.datetime,
        updated_at: datetime.datetime,
    ) -> Record: ...
    async def update_status_code(
        self,
        conn: Connection,
        *,
        message_id: int,
        status_code: int,
        updated_at: datetime.datetime,
    ) -> Record: ...
    async def get_all_messages_by_author_id(
        self, conn: Connection, *, id: int
    ) -> Record: ...
    async def get_lookup_messages_by_author_id(
        self, conn: Connection, *, id: int, lookup: str
    ) -> Record: ...
    async def create_message_number(
        self,
        conn: Connection,
        *,
        number: str,
        message_id: int,
    ) -> Record: ...
    async def get_user_messages(
        self, conn: Connection, *, user_id: int, status_code: int
    ) -> Record: ...

class Queries(
    UsersQueriesMixin,
    StatusesQueriesMixin,
    MessagesQueriesMixin,
): ...

queries: Queries
